name: CI
on:
  push:
  release:
    types: [created]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    strategy:
      matrix:
        include:
          - name: pgparquet-linux-aarch64
            os: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
          - name: pgparquet-linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - name: pgparquet-macos-aarch64
            os: macos-latest
            target: aarch64-apple-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Lint
        run: |
          cargo clippy
          cargo fmt --check
      - name: Test
        run: cargo test
      - name: Build binary
        run: |
          cargo build --release --target ${{ matrix.target }}
      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: target/${{ matrix.target }}/release/pgparquet
